spring:
  application:
    name: PlaceOrder
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  jpa:
    # hibernate:
    #   ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
