spring:
  application:
    name: PlaceOrder
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
